# Generated by Django 5.2.6 on 2025-09-18 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('income', 'Entrada'), ('outcome', 'Saída')], default='income', max_length=10, verbose_name='Tipo de transação'),
        ),
    ]
