# Generated by Django 5.2.6 on 2025-09-19 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_transaction_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='installment_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Número da Parcela'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='is_installment',
            field=models.BooleanField(default=False, verbose_name='É parcela?'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='parent_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installments', to='finance.transaction', verbose_name='Transação Principal'),
        ),
    ]
